export const LINKS = {
  invoicesVIG: "/invoices/list/VIG",
  invoicesANU: "/invoices/list/ANU",
  create_invoice: "/invoice/create/",
  charts : "/charts/view/",
  invoices_update : "/invoices/update/",
  invoices_view : "/invoices/view/",
  invoices_delete : "/invoices/delete/",
  aggregation01: "/aggregation01/view/",
  aggregation02: "/aggregation02/view/",
  aggregation03: "/aggregation03/view/",
  aggregation04: "/aggregation04/view/",
  product_test: "/product_test/view/",
  inventories: "/inventories/view/",
  products: "/products/view/",
  products_create: "/products/create/",
  products_update: "/products/update/",
  products_delete: "/products/delete/",
  purchase_orders: "/purchase-orders/view/",
  transport_routes: "/transport-routes/view/",
  suppliers: "/suppliers/view/",
  suppliers_create: "/suppliers/create/",
  suppliers_update: "/suppliers/update/",
  suppliers_delete: "/suppliers/delete/",
};
